# -*- coding: utf-8 -*-
"""FinalHealthGuard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_nbLPCovkMl2q30PQGKnBVz4WYB6eWx

Install Libraries
"""

# ============================================================
# HealthGuardian
# Install Required Libraries
# ============================================================

!pip -q install langgraph
!pip -q install langchain
!pip -q install langchain-core
!pip -q install langchain-community
!pip -q install langchain-groq

!pip -q install streamlit

!pip -q install pandas

!pip -q install python-dotenv

!pip -q install pytesseract

!pip -q install PyMuPDF

!pip -q install pillow

!sudo apt-get -y install tesseract-ocr

# ============================================================
# Import Libraries
# ============================================================

import os
import json
import sqlite3
import logging
import re

from typing import TypedDict
from typing import List
from typing import Dict

from datetime import datetime
from datetime import timedelta

import pandas as pd

from PIL import Image

import fitz

import pytesseract

from langgraph.graph import StateGraph
from langgraph.graph import END

from langchain_groq import ChatGroq

from IPython.display import display

print("✅ Libraries Imported Successfully")

"""Groq API"""

# ============================================================
# Load Groq API
# ============================================================

import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("Enter your Groq API Key: ")

llm = ChatGroq(

    model="llama-3.3-70b-versatile",

    temperature=0.2

)

print("✅ Groq Connected Successfully")

"""SQLite Database"""

# ============================================================
# SQLite Database
# ============================================================

connection = sqlite3.connect(

    "healthguardian.db",

    check_same_thread=False

)

cursor = connection.cursor()

print("✅ Database Connected")

"""Create Tables"""

# ============================================================
# Patient Table
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS patients(

id INTEGER PRIMARY KEY AUTOINCREMENT,

name TEXT,

age INTEGER,

gender TEXT,

blood_group TEXT,

height REAL,

weight REAL,

allergies TEXT,

category TEXT,

doctor_name TEXT,

doctor_contact TEXT,

emergency_contact TEXT

)

""")

# ============================================================
# Prescription Table
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS prescriptions(

id INTEGER PRIMARY KEY AUTOINCREMENT,

patient_id INTEGER,

ocr_text TEXT,

uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)

""")

# ============================================================
# Medicines
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS medicines(

id INTEGER PRIMARY KEY AUTOINCREMENT,

patient_id INTEGER,

medicine_name TEXT,

dosage TEXT,

frequency TEXT,

duration TEXT,

tablets INTEGER,

refill_date TEXT

)

""")

# ============================================================
# Wellness
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS wellness(

id INTEGER PRIMARY KEY AUTOINCREMENT,

patient_id INTEGER,

status TEXT,

symptoms TEXT,

severity TEXT,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)

""")

# ============================================================
# Appointment
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS appointments(

id INTEGER PRIMARY KEY AUTOINCREMENT,

patient_id INTEGER,

doctor TEXT,

date TEXT,

time TEXT,

status TEXT

)

""")

# ============================================================
# Emergency
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS emergencies(

id INTEGER PRIMARY KEY AUTOINCREMENT,

patient_id INTEGER,

location TEXT,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)

""")

# ============================================================
# Caregiver
# ============================================================

cursor.execute("""

CREATE TABLE IF NOT EXISTS caregivers(

id INTEGER PRIMARY KEY AUTOINCREMENT,

patient_id INTEGER,

name TEXT,

phone TEXT,

email TEXT

)

""")

connection.commit()

print("✅ All Tables Created Successfully")

"""LangGraph State"""

# ============================================================
# Shared LangGraph State
# ============================================================

class HealthGuardianState(TypedDict):

    patient_profile: dict

    patient_category: dict

    prescription: dict

    medicines: list

    reminders: list

    wellness: dict

    emergency: dict

    caregiver_notifications: list

    appointment: dict

    ai_response: str

print("✅ LangGraph State Ready")

"""Patient Registration Agent"""

# ============================================================
# HealthGuardian
# Patient Registration Agent
# ============================================================

import re

class PatientRegistrationAgent:

    VALID_BLOOD_GROUPS = {
        "A+","A-","B+","B-",
        "AB+","AB-","O+","O-"
    }

    def __init__(self):
        pass

    # --------------------------------------------------------

    def validate_name(self, name):

        if len(name.strip()) < 2:
            raise ValueError("Invalid Name")

        return name.title()

    # --------------------------------------------------------

    def validate_age(self, age):

        age = int(age)

        if age <= 0 or age > 120:
            raise ValueError("Invalid Age")

        return age

    # --------------------------------------------------------

    def validate_gender(self, gender):

        gender = gender.title()

        allowed = ["Male","Female","Other"]

        if gender not in allowed:
            raise ValueError("Invalid Gender")

        return gender

    # --------------------------------------------------------

    def validate_blood_group(self, bg):

        bg = bg.upper()

        if bg not in self.VALID_BLOOD_GROUPS:
            raise ValueError("Invalid Blood Group")

        return bg

    # --------------------------------------------------------

    def validate_phone(self, phone):

        phone = str(phone)

        if not re.fullmatch(r"\d{10}", phone):
            raise ValueError("Invalid Phone Number")

        return phone

    # --------------------------------------------------------

    def register_patient(self, profile):

        cursor.execute("""

        INSERT INTO patients(

        name,
        age,
        gender,
        blood_group,
        height,
        weight,
        allergies,
        category,
        doctor_name,
        doctor_contact,
        emergency_contact

        )

        VALUES(?,?,?,?,?,?,?,?,?,?,?)

        """,

        (

        self.validate_name(profile["name"]),

        self.validate_age(profile["age"]),

        self.validate_gender(profile["gender"]),

        self.validate_blood_group(profile["blood_group"]),

        profile["height"],

        profile["weight"],

        profile["allergies"],

        profile["category"],

        profile["doctor_name"],

        self.validate_phone(profile["doctor_contact"]),

        self.validate_phone(profile["emergency_contact"])

        )

        )

        connection.commit()

        patient_id = cursor.lastrowid

        return patient_id


# ============================================================
# LangGraph Node
# ============================================================

def patient_registration_node(state):

    agent = PatientRegistrationAgent()

    patient_id = agent.register_patient(

        state["patient_profile"]

    )

    state["patient_profile"]["patient_id"] = patient_id

    print(f"✅ Patient Registered Successfully")

    print(f"Patient ID : {patient_id}")

    return state

"""Test Module 7"""

sample_state = {

"patient_profile":{

"name":"Rahul Sharma",

"age":65,

"gender":"Male",

"blood_group":"O+",

"height":172,

"weight":70,

"allergies":"None",

"category":"Elderly Citizen",

"doctor_name":"Dr Mehta",

"doctor_contact":"9876543210",

"emergency_contact":"9123456789"

}

}

result = patient_registration_node(sample_state)

print(result)

"""Patient Category Agent"""

# ============================================================
# HealthGuardian
# Patient Category Agent
# ============================================================

class PatientCategoryAgent:

    CATEGORIES = [
        "Elderly Citizen",
        "Chronic Disease Patient",
        "Accident Recovery",
        "Pre-Surgery",
        "Post-Surgery",
        "Long-term Medication",
        "General Health"
    ]

    def __init__(self):
        pass

    # --------------------------------------------------------

    def recommend_category(self, profile):

        age = profile.get("age", 0)

        allergies = profile.get("allergies", "").lower()

        if age >= 60:
            return "Elderly Citizen"

        elif "diabetes" in allergies or "hypertension" in allergies:
            return "Chronic Disease Patient"

        else:
            return "General Health"

    # --------------------------------------------------------

    def validate_category(self, category):

        if category not in self.CATEGORIES:
            raise ValueError("Invalid Patient Category")

        return category

    # --------------------------------------------------------

    def update_database(self, patient_id, category):

        cursor.execute(
            """
            UPDATE patients
            SET category=?
            WHERE id=?
            """,
            (category, patient_id)
        )

        connection.commit()

# ============================================================
# LangGraph Node
# ============================================================

def patient_category_node(state):

    agent = PatientCategoryAgent()

    profile = state["patient_profile"]

    # Use selected category if provided, otherwise recommend one
    selected_category = profile.get("category")

    if not selected_category:
        selected_category = agent.recommend_category(profile)

    selected_category = agent.validate_category(selected_category)

    patient_id = profile["patient_id"]

    agent.update_database(
        patient_id,
        selected_category
    )

    state["patient_category"] = {
        "category": selected_category
    }

    state["patient_profile"]["category"] = selected_category

    print("✅ Patient Category Selected")

    print("Category :", selected_category)

    return state

"""⭐ Test Module 8"""

sample_state = {

    "patient_profile": {

        "patient_id": 1,

        "name": "Rahul Sharma",

        "age": 67,

        "gender": "Male",

        "blood_group": "O+",

        "height": 172,

        "weight": 70,

        "allergies": "None",

        "doctor_name": "Dr Mehta",

        "doctor_contact": "9876543210",

        "emergency_contact": "9123456789"

    }

}

result = patient_category_node(sample_state)

print(result["patient_category"])

"""Prescription Upload & OCR Agent"""

# ============================================================
# HealthGuardian
# Prescription Upload & OCR Agent
# ============================================================

import json
import fitz
import pytesseract
from PIL import Image
from pathlib import Path
import re

# ============================================================
# OCR Engine
# ============================================================

class PrescriptionOCR:

    def extract_text(self, file_path):

        file_path = Path(file_path)

        if not file_path.exists():
            raise FileNotFoundError(f"{file_path} not found.")

        suffix = file_path.suffix.lower()

        # ---------- PDF ----------
        if suffix == ".pdf":

            text = ""

            document = fitz.open(file_path)

            for page in document:
                page_text = page.get_text()

                if page_text.strip():
                    text += page_text + "\n"

                else:
                    pix = page.get_pixmap(dpi=300)
                    image = Image.frombytes(
                        "RGB",
                        [pix.width, pix.height],
                        pix.samples
                    )
                    text += pytesseract.image_to_string(image)

            document.close()

            return text

        # ---------- Image ----------

        elif suffix in [".png", ".jpg", ".jpeg"]:

            image = Image.open(file_path)

            return pytesseract.image_to_string(image)

        else:

            raise ValueError("Unsupported file format.")

# ============================================================
# Medicine Extraction using Groq
# ============================================================

class PrescriptionParser:

    def __init__(self):

        self.prompt = """
You are an expert medical assistant.

Extract every medicine from the prescription.

Return ONLY valid JSON.

Example:

[
{
"medicine_name":"Paracetamol",
"dosage":"500 mg",
"frequency":"Twice Daily",
"duration":"5 Days"
}
]

Do not explain anything.
"""

    def extract_medicines(self, text):

        response = llm.invoke(

            self.prompt + "\n\nPrescription:\n" + text

        )

        try:

            medicines = json.loads(response.content)

            return medicines

        except Exception:

            return []

# ============================================================
# Prescription Agent
# ============================================================

class PrescriptionAgent:

    def __init__(self):

        self.ocr = PrescriptionOCR()

        self.parser = PrescriptionParser()

    # --------------------------------------------------------

    def process(self,
                patient_id,
                file_path):

        text = self.ocr.extract_text(file_path)

        medicines = self.parser.extract_medicines(text)

        cursor.execute(

        """

        INSERT INTO prescriptions(

        patient_id,

        ocr_text

        )

        VALUES(?,?)

        """,

        (

        patient_id,

        text

        )

        )

        connection.commit()

        return {

            "ocr_text": text,

            "medicines": medicines

        }

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def prescription_node(state):

    agent = PrescriptionAgent()

    patient_id = state["patient_profile"]["patient_id"]

    file_path = state["prescription"]["file_path"]

    result = agent.process(

        patient_id,

        file_path

    )

    state["prescription"] = {

        "ocr_text": result["ocr_text"]

    }

    state["medicines"] = result["medicines"]

    print("✅ Prescription Processed Successfully")

    print(f"Medicines Found : {len(result['medicines'])}")

    return state

"""⭐ Test Cell"""

sample_state = {

    "patient_profile": {

        "patient_id": 1

    },

    "prescription": {

        "file_path": "sample_prescription.pdf"

    }

}

result = prescription_node(sample_state)

print(result["medicines"])

"""Medicine Reminder Agent"""

# ============================================================
# HealthGuardian
# Medicine Reminder Agent
# ============================================================

from datetime import datetime, timedelta

class MedicineReminderAgent:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # Generate Reminder Times
    # --------------------------------------------------------

    def generate_schedule(self, frequency):

        frequency = frequency.lower()

        if "once" in frequency:
            return ["08:00"]

        elif "twice" in frequency:
            return ["08:00", "20:00"]

        elif "three" in frequency:
            return ["08:00", "14:00", "20:00"]

        elif "four" in frequency:
            return ["06:00", "12:00", "18:00", "22:00"]

        else:
            return ["08:00"]

    # --------------------------------------------------------
    # Calculate Refill Date
    # --------------------------------------------------------

    def calculate_refill_date(self, tablets, frequency):

        frequency = frequency.lower()

        if "once" in frequency:
            doses = 1

        elif "twice" in frequency:
            doses = 2

        elif "three" in frequency:
            doses = 3

        elif "four" in frequency:
            doses = 4

        else:
            doses = 1

        days = tablets // doses

        refill_date = datetime.now() + timedelta(days=days)

        return refill_date.strftime("%Y-%m-%d")

    # --------------------------------------------------------
    # Save Medicine
    # --------------------------------------------------------

    def save_medicine(self, patient_id, medicine):

        schedule = self.generate_schedule(
            medicine["frequency"]
        )

        refill_date = self.calculate_refill_date(
            medicine.get("tablets", 30),
            medicine["frequency"]
        )

        cursor.execute(
            """
            INSERT INTO medicines(
                patient_id,
                medicine_name,
                dosage,
                frequency,
                duration,
                tablets,
                refill_date
            )
            VALUES(?,?,?,?,?,?,?)
            """,
            (
                patient_id,
                medicine["medicine_name"],
                medicine["dosage"],
                medicine["frequency"],
                medicine["duration"],
                medicine.get("tablets", 30),
                refill_date
            )
        )

        connection.commit()

        return {
            "medicine_name": medicine["medicine_name"],
            "schedule": schedule,
            "refill_date": refill_date
        }

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def medicine_reminder_node(state):

    agent = MedicineReminderAgent()

    patient_id = state["patient_profile"]["patient_id"]

    reminders = []

    medicines = state.get("medicines", [])

    for medicine in medicines:

        reminder = agent.save_medicine(
            patient_id,
            medicine
        )

        reminders.append(reminder)

    state["reminders"] = reminders

    print("✅ Medicine Reminder Created")

    print(f"Total Medicines : {len(reminders)}")

    return state

"""⭐ Test Module"""

sample_state = {

    "patient_profile": {
        "patient_id": 1
    },

    "medicines": [

        {
            "medicine_name": "Paracetamol",
            "dosage": "500 mg",
            "frequency": "Twice Daily",
            "duration": "5 Days",
            "tablets": 20
        },

        {
            "medicine_name": "Vitamin D",
            "dosage": "1000 IU",
            "frequency": "Once Daily",
            "duration": "30 Days",
            "tablets": 30
        }

    ]
}

result = medicine_reminder_node(sample_state)

print(result["reminders"])

"""Daily Wellness Check Agent"""

# ============================================================
# HealthGuardian
# Daily Wellness Check Agent
# ============================================================

class WellnessAgent:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # Save Wellness Record
    # --------------------------------------------------------

    def save_record(
        self,
        patient_id,
        status,
        symptoms,
        severity
    ):

        cursor.execute(
            """
            INSERT INTO wellness(
                patient_id,
                status,
                symptoms,
                severity
            )
            VALUES(?,?,?,?)
            """,
            (
                patient_id,
                status,
                symptoms,
                severity
            )
        )

        connection.commit()

    # --------------------------------------------------------
    # AI Wellness Advice
    # --------------------------------------------------------

    def generate_advice(
        self,
        status,
        symptoms
    ):

        prompt = f"""
You are an experienced healthcare assistant.

Patient Status:
{status}

Symptoms:
{symptoms}

Give 3 simple wellness suggestions.

Always remind the patient to consult a qualified healthcare professional for persistent or severe symptoms.

Keep the answer under 120 words.
"""

        response = llm.invoke(prompt)

        return response.content

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def wellness_node(state):

    agent = WellnessAgent()

    patient_id = state["patient_profile"]["patient_id"]

    wellness = state.get("wellness", {})

    status = wellness.get("status", "Good")

    symptoms = wellness.get("symptoms", "None")

    severity = wellness.get("severity", "Low")

    # Save to Database
    agent.save_record(
        patient_id,
        status,
        symptoms,
        severity
    )

    # AI Advice
    advice = agent.generate_advice(
        status,
        symptoms
    )

    state["wellness"] = {

        "status": status,

        "symptoms": symptoms,

        "severity": severity,

        "advice": advice

    }

    # Decide if emergency workflow should be triggered
    state["emergency"] = {

        "trigger": severity.lower() in [
            "high",
            "critical",
            "severe"
        ]

    }

    print("✅ Wellness Check Completed")

    print("Emergency Trigger:",
          state["emergency"]["trigger"])

    return state

"""⭐ Test Module"""

sample_state = {

    "patient_profile": {
        "patient_id": 1
    },

    "wellness": {

        "status": "Unwell",

        "symptoms": "High fever and dizziness",

        "severity": "High"

    }

}

result = wellness_node(sample_state)

print(result["wellness"])

print(result["emergency"])

"""Emergency Detection Agent"""

# ============================================================
# HealthGuardian
# Emergency Detection Agent
# ============================================================

from datetime import datetime

class EmergencyDetectionAgent:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # Detect Emergency
    # --------------------------------------------------------

    def detect_emergency(self, wellness):

        severity = wellness.get("severity", "").lower()

        emergency_keywords = [
            "high",
            "severe",
            "critical"
        ]

        return severity in emergency_keywords

    # --------------------------------------------------------
    # Save Emergency Event
    # --------------------------------------------------------

    def save_event(
        self,
        patient_id,
        location
    ):

        cursor.execute(
            """
            INSERT INTO emergencies(
                patient_id,
                location
            )
            VALUES(?,?)
            """,
            (
                patient_id,
                location
            )
        )

        connection.commit()

    # --------------------------------------------------------
    # Generate Alert
    # --------------------------------------------------------

    def generate_alert(
        self,
        patient_name,
        location
    ):

        return f"""
🚨 EMERGENCY ALERT 🚨

Patient : {patient_name}

Location : {location}

Immediate medical attention may be required.

Please contact the caregiver or emergency services immediately.
"""

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def emergency_detection_node(state):

    agent = EmergencyDetectionAgent()

    patient = state["patient_profile"]

    emergency = state.get("emergency", {})

    location = emergency.get(
        "location",
        "Location Unavailable"
    )

    detected = agent.detect_emergency(
        state["wellness"]
    )

    if detected:

        agent.save_event(

            patient["patient_id"],

            location

        )

        alert = agent.generate_alert(

            patient["name"],

            location

        )

        state["emergency"] = {

            "trigger": True,

            "location": location,

            "alert": alert

        }

        print("🚨 Emergency Detected")

    else:

        state["emergency"] = {

            "trigger": False,

            "location": location,

            "alert": ""

        }

        print("✅ No Emergency Detected")

    return state

"""⭐ Test Module"""

sample_state = {

    "patient_profile": {

        "patient_id": 1,

        "name": "Rahul Sharma"

    },

    "wellness": {

        "status": "Unwell",

        "symptoms": "Chest Pain",

        "severity": "High"

    },

    "emergency": {

        "location": "Koppal, Karnataka"

    }

}

result = emergency_detection_node(sample_state)

print(result["emergency"]["alert"])

"""Caregiver Notification Agent"""

# ============================================================
# HealthGuardian
# Caregiver Notification Agent
# ============================================================

from datetime import datetime

class CaregiverNotificationAgent:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # Get Caregivers from Database
    # --------------------------------------------------------

    def get_caregivers(self, patient_id):

        cursor.execute(
            """
            SELECT name, phone, email
            FROM caregivers
            WHERE patient_id=?
            """,
            (patient_id,)
        )

        rows = cursor.fetchall()

        caregivers = []

        for row in rows:

            caregivers.append({

                "name": row[0],

                "phone": row[1],

                "email": row[2]

            })

        return caregivers

    # --------------------------------------------------------
    # SMS Template
    # --------------------------------------------------------

    def generate_sms(self, caregiver_name, patient_name, location):

        return f"""
Emergency Alert!

Dear {caregiver_name},

{patient_name} may require immediate medical attention.

Location:
{location}

Please contact the patient immediately.
"""

    # --------------------------------------------------------
    # Email Template
    # --------------------------------------------------------

    def generate_email(self, caregiver_name, patient_name, location):

        return f"""
Subject: HealthGuardian Emergency Alert

Dear {caregiver_name},

HealthGuardian has detected a possible emergency.

Patient:
{patient_name}

Location:
{location}

Please contact the patient or emergency services immediately.

Regards,
HealthGuardian AI
"""

    # --------------------------------------------------------
    # Placeholder Notification
    # --------------------------------------------------------

    def send_notifications(

        self,

        caregivers,

        patient_name,

        location

    ):

        sent_notifications = []

        for caregiver in caregivers:

            sms = self.generate_sms(

                caregiver["name"],

                patient_name,

                location

            )

            email = self.generate_email(

                caregiver["name"],

                patient_name,

                location

            )

            print("=" * 60)

            print(f"SMS to {caregiver['phone']}")

            print(sms)

            print("-" * 60)

            print(f"Email to {caregiver['email']}")

            print(email)

            print("=" * 60)

            sent_notifications.append({

                "caregiver": caregiver["name"],

                "phone": caregiver["phone"],

                "email": caregiver["email"],

                "status": "Notification Generated"

            })

        return sent_notifications

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def caregiver_notification_node(state):

    if not state["emergency"]["trigger"]:

        print("✅ No Emergency - Notification Skipped")

        state["caregiver_notifications"] = []

        return state

    agent = CaregiverNotificationAgent()

    patient = state["patient_profile"]

    patient_id = patient["patient_id"]

    patient_name = patient["name"]

    location = state["emergency"]["location"]

    caregivers = agent.get_caregivers(

        patient_id

    )

    notifications = agent.send_notifications(

        caregivers,

        patient_name,

        location

    )

    state["caregiver_notifications"] = notifications

    print("✅ Caregiver Notification Completed")

    return state

"""⭐ Test Module"""

cursor.execute("""

INSERT INTO caregivers(

patient_id,

name,

phone,

email

)

VALUES(?,?,?,?)

""",

(

1,

"Priya Sharma",

"9876543210",

"priya@email.com"

)

)

connection.commit()

sample_state = {

    "patient_profile": {

        "patient_id": 1,

        "name": "Rahul Sharma"

    },

    "emergency": {

        "trigger": True,

        "location": "Koppal, Karnataka"

    }

}

result = caregiver_notification_node(sample_state)

print(result["caregiver_notifications"])

"""AI Health Assistant"""

# ============================================================
# HealthGuardian
# AI Health Assistant
# ============================================================

class AIHealthAssistant:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # General Health Chat
    # --------------------------------------------------------

    def answer_question(self, question):

        prompt = f"""
You are HealthGuardian AI.

You are a helpful healthcare assistant.

Rules:

1. Answer only general health questions.

2. Never diagnose diseases.

3. Never prescribe medicines.

4. Always recommend consulting a qualified doctor for serious or persistent symptoms.

Question:

{question}

Provide a clear and simple answer.
"""

        response = llm.invoke(prompt)

        return response.content

    # --------------------------------------------------------
    # Explain Medicine
    # --------------------------------------------------------

    def explain_medicine(self, medicine_name):

        prompt = f"""
Explain this medicine in simple language.

Medicine:

{medicine_name}

Include:

• Purpose
• Common side effects
• Important precautions

Keep the answer under 150 words.

Do not give personalized medical advice.
"""

        response = llm.invoke(prompt)

        return response.content

    # --------------------------------------------------------
    # Explain Prescription
    # --------------------------------------------------------

    def explain_prescription(self, prescription_text):

        prompt = f"""
Explain the following prescription in very simple language.

Prescription:

{prescription_text}

Explain:

• Medicines
• Dosage
• Frequency
• Duration

Return a patient-friendly explanation.
"""

        response = llm.invoke(prompt)

        return response.content

    # --------------------------------------------------------
    # Healthy Lifestyle Suggestions
    # --------------------------------------------------------

    def healthy_habits(self):

        prompt = """
Suggest 10 healthy daily habits for elderly people.

Keep them simple.

Return as bullet points.
"""

        response = llm.invoke(prompt)

        return response.content

    # --------------------------------------------------------
    # Emergency Detection from User Message
    # --------------------------------------------------------

    def detect_emergency_keywords(self, text):

        emergency_words = [

            "chest pain",

            "heart attack",

            "can't breathe",

            "breathing problem",

            "stroke",

            "unconscious",

            "fainted",

            "severe bleeding",

            "blood vomiting",

            "collapsed"

        ]

        text = text.lower()

        for word in emergency_words:

            if word in text:

                return True

        return False

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def ai_health_assistant_node(state):

    assistant = AIHealthAssistant()

    question = state.get("user_question", "")

    answer = assistant.answer_question(question)

    emergency = assistant.detect_emergency_keywords(question)

    state["ai_response"] = answer

    if emergency:

        state["emergency"] = {

            "trigger": True,

            "reason": "Emergency keywords detected"

        }

        print("🚨 Emergency Keywords Detected")

    else:

        state["emergency"] = {

            "trigger": False

        }

    print("✅ AI Response Generated")

    return state

"""⭐ Test Module"""

sample_state = {

    "user_question":

    "I have chest pain and difficulty breathing."

}

result = ai_health_assistant_node(sample_state)

print(result["ai_response"])

print(result["emergency"])

"""Appointment Management Agent"""

# ============================================================
# HealthGuardian
# Appointment Management Agent
# ============================================================

from datetime import datetime

class AppointmentAgent:

    def __init__(self):
        pass

    # --------------------------------------------------------
    # Doctor Recommendation
    # --------------------------------------------------------

    def recommend_doctor(self, category):

        doctors = {

            "Elderly Citizen": ("Dr. Sharma", "Geriatrician"),

            "Chronic Disease Patient": ("Dr. Mehta", "Internal Medicine"),

            "Accident Recovery": ("Dr. Rao", "Orthopedic Surgeon"),

            "Pre-Surgery": ("Dr. Patel", "General Surgeon"),

            "Post-Surgery": ("Dr. Patel", "General Surgeon"),

            "Long-term Medication": ("Dr. Gupta", "General Physician"),

            "General Health": ("Dr. Kumar", "Family Physician")

        }

        return doctors.get(
            category,
            ("Dr. Kumar", "Family Physician")
        )

    # --------------------------------------------------------
    # Book Appointment
    # --------------------------------------------------------

    def book_appointment(

        self,

        patient_id,

        doctor,

        speciality,

        date,

        time

    ):

        cursor.execute(
            """
            INSERT INTO appointments(
                patient_id,
                doctor,
                date,
                time,
                status
            )
            VALUES(?,?,?,?,?)
            """,
            (
                patient_id,
                doctor,
                date,
                time,
                "Booked"
            )
        )

        connection.commit()

        return cursor.lastrowid

    # --------------------------------------------------------
    # View Appointments
    # --------------------------------------------------------

    def view_appointments(self, patient_id):

        cursor.execute(
            """
            SELECT
            doctor,
            date,
            time,
            status
            FROM appointments
            WHERE patient_id=?
            """,
            (patient_id,)
        )

        rows = cursor.fetchall()

        appointments = []

        for row in rows:

            appointments.append({

                "doctor": row[0],

                "date": row[1],

                "time": row[2],

                "status": row[3]

            })

        return appointments

    # --------------------------------------------------------
    # Cancel Appointment
    # --------------------------------------------------------

    def cancel_appointment(self, appointment_id):

        cursor.execute(
            """
            UPDATE appointments
            SET status='Cancelled'
            WHERE id=?
            """,
            (appointment_id,)
        )

        connection.commit()

        return True

    # --------------------------------------------------------
    # Reschedule Appointment
    # --------------------------------------------------------

    def reschedule(

        self,

        appointment_id,

        new_date,

        new_time

    ):

        cursor.execute(
            """
            UPDATE appointments
            SET
            date=?,
            time=?,
            status='Rescheduled'
            WHERE id=?
            """,
            (
                new_date,
                new_time,
                appointment_id
            )
        )

        connection.commit()

        return True

"""⭐ LangGraph Node"""

# ============================================================
# LangGraph Node
# ============================================================

def appointment_node(state):

    agent = AppointmentAgent()

    patient = state["patient_profile"]

    patient_id = patient["patient_id"]

    category = patient["category"]

    doctor, speciality = agent.recommend_doctor(category)

    appointment = state.get("appointment", {})

    date = appointment.get("date", "2026-08-01")

    time = appointment.get("time", "10:00 AM")

    appointment_id = agent.book_appointment(

        patient_id,

        doctor,

        speciality,

        date,

        time

    )

    appointments = agent.view_appointments(

        patient_id

    )

    state["appointment"] = {

        "appointment_id": appointment_id,

        "doctor": doctor,

        "speciality": speciality,

        "date": date,

        "time": time,

        "appointments": appointments

    }

    print("✅ Appointment Booked Successfully")

    return state

"""⭐ Test Module"""

sample_state = {

    "patient_profile": {

        "patient_id": 1,

        "category": "Elderly Citizen"

    },

    "appointment": {

        "date": "2026-08-15",

        "time": "11:30 AM"

    }

}

result = appointment_node(sample_state)

print(result["appointment"])

# ============================================================
# Prescription Upload LangGraph Node
# ============================================================

def prescription_upload_node(state):

    agent = PrescriptionAgent()

    file_path = state.get("prescription_file")

    if not file_path:

        print("No prescription uploaded.")

        state["medicines"] = []

        return state

    result = agent.process_prescription(file_path)

    try:

        import json

        parsed = json.loads(result)

        state["prescription"] = parsed

        state["medicines"] = parsed.get("medicines", [])

        print("✅ Prescription Processed Successfully")

    except Exception:

        state["prescription"] = {}

        state["medicines"] = []

        print("❌ Unable to process prescription")

    return state

"""Complete LangGraph Workflow"""

# ============================================================
# HealthGuardian
# Complete LangGraph Workflow
# ============================================================

from typing import TypedDict, Dict, Any
from langgraph.graph import StateGraph, END

# ============================================================
# State Definition
# ============================================================

class HealthGuardianState(TypedDict, total=False):

    patient_profile: Dict[str, Any]

    patient_category: Dict[str, Any]

    prescription: Dict[str, Any]

    medicines: list

    reminders: list

    wellness: Dict[str, Any]

    emergency: Dict[str, Any]

    caregiver_notifications: list

    appointment: Dict[str, Any]

    user_question: str

    ai_response: str

# ============================================================
# Build Workflow
# ============================================================

workflow = StateGraph(HealthGuardianState)

# ============================================================
# Add Nodes
# ============================================================

workflow.add_node(
    "Patient Registration",
    patient_registration_node
)

workflow.add_node(
    "Patient Category",
    patient_category_node
)

workflow.add_node(
    "Prescription Upload",
    prescription_upload_node
)

workflow.add_node(
    "Medicine Reminder",
    medicine_reminder_node
)

workflow.add_node(
    "Daily Wellness",
    wellness_node
)

workflow.add_node(
    "Emergency Detection",
    emergency_detection_node
)

workflow.add_node(
    "Caregiver Notification",
    caregiver_notification_node
)

workflow.add_node(
    "AI Health Assistant",
    ai_health_assistant_node
)

workflow.add_node(
    "Appointment",
    appointment_node)

# ============================================================
# Define Flow
# ============================================================

workflow.set_entry_point("Patient Registration")

workflow.add_edge(
    "Patient Registration",
    "Patient Category"
)

workflow.add_edge(
    "Patient Category",
    "Prescription Upload"
)

workflow.add_edge(
    "Prescription Upload",
    "Medicine Reminder"
)

workflow.add_edge(
    "Medicine Reminder",
    "Daily Wellness"
)

workflow.add_edge(
    "Daily Wellness",
    "Emergency Detection"
)

workflow.add_edge(
    "Emergency Detection",
    "Caregiver Notification"
)

workflow.add_edge(
    "Caregiver Notification",
    "AI Health Assistant"
)

workflow.add_edge(
    "AI Health Assistant",
    "Appointment"
)

workflow.add_edge(
    "Appointment",
    END
)

# ============================================================
# Compile
# ============================================================

app = workflow.compile()

print("✅ HealthGuardian Workflow Created Successfully!")

initial_state = {

    "patient_profile": {

        "patient_id": 1,

        "name": "Rahul Sharma",

        "age": 68,

        "gender": "Male",

        "blood_group": "O+",

        "height": 170,

        "weight": 72,

        "allergies": "None",

        "emergency_contact": "9876543210",

        "doctor_name": "Dr. Sharma",

        "doctor_contact": "9876500000"

    },

    "patient_category": {

        "category": "Elderly Citizen"

    },

    "prescription_file": "sample_prescription.pdf",

    "wellness": {

        "status": "Good",

        "symptoms": "None",

        "severity": "Low"

    },

    "user_question": "How can I improve my heart health?"

}
